name: Deploy API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          
      - name: Run tests
        run: |
          pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Install CDK
        run: |
          npm install -g aws-cdk
          
      - name: Create Lambda deployment package
        run: |
          # Create deployment directory
          mkdir -p lambda-package
          
          # Copy source code
          cp -r src/* lambda-package/
          
          # Install dependencies into the package
          pip install -r requirements.txt -t lambda-package/
          
          # Create zip file
          cd lambda-package
          zip -r ../lambda-deployment.zip .
          cd ..
          
      - name: Install CDK dependencies
        run: |
          cd infrastructure
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy infrastructure
        env:
          JSII_SILENCE_WARNING_DEPRECATED_NODE_VERSION: true
        run: |
          cd infrastructure
          cdk deploy --require-approval never